feat: allow version to be specified
Bearer/bearer-action pull request #21
Opened 2023-04-25 12:48 UTC by didroe

Allows a version to be specified as an input to the action. This version must match a release name, with or without the `v` prefix. eg. `1.4.0` or `v1.4.0` are both acceptable values. 

By default we continue to use the latest version.

To support this change, we switch to downloading the executable and running it under the Github runner, rather than using the docker image.

We probably should make this a nodejs action and use Github's libraries for downloading/caching. But I didn't want to take on too big a change.

2023-04-25 14:59 UTC, gotbadger requested changes
```
Run VERSION=""
  VERSION=""
  VERSION="${VERSION#v}"
  
  curl -sfL https://raw.githubusercontent.com/Bearer/bearer/main/contrib/install.sh | sh -s -- -b "$RUNNER_TEMP" "v$VERSION"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Bearer/bearer info checking GitHub for tag 'v'
Bearer/bearer crit unable to find 'v' - use 'latest' or see https://github.com/Bearer/bearer/releases for details
```

Think there is an issue with how v is being parsed

https://github.com/gotbadger/bear-publishing/actions/runs/4798910100/jobs/8537833121

2023-04-26 08:42 UTC, didroe commented
@gotbadger Should be fixed now

2023-04-26 10:23 UTC, gotbadger commented
Seems like the output is not captured https://github.com/gotbadger/bear-publishing/actions/runs/4798910100/jobs/8556511330 from the binary

2023-04-26 10:43 UTC, didroe commented
@gotbadger I've fixed the outputs

2023-04-26 11:03 UTC, gotbadger approved these changes
Think there might be some doc changes required in the main site so just check in with @markmichon

2023-04-26 11:24 UTC, merged